### ISSUE TITLE
Add tracking by name. 

### ISSUE THREAD

**Issue by jbucky86** [jptrsn/ESP32-mqtt-room#32]
i found an app that somehow permanently changes the name in the UUID. Well until a reboot. For IOS. “nRF connect”. Even when forced closed and locking the iPhone. Not sure how. But it does. It might be something to look in to

**Comment by jptrsn** [comment]
@jbucky86 I'm not sure how it would be put into practice integrating into the mqtt_room, since names do not have any uniqueness requirement for BLE devices. I also do not own any iOS devices, so cannot test tracking an iPhone here in my house. I believe you should be able to set up a beacon in the NRF Connect app, which would then be trackable. However, I don't know if it will run in the background.
